#!/bin/bash

# Welcome to the Fully Automated Paradigm Shifter! (FAPS)
# This script was designed to send email motivation to your team. Or spam your
# enemies. Whatever.

# Who are you sending this to? Note the differences in spacing. The first emails
# are being BCC'd with the -b option in the mail command where as the final
# email address is a throw away. mail x needs one visible account to send with a
# bcc. choose wisely
#distro='bcc1@.com,bcc2@.com, admin@faps.com'

# who is this coming from?
#from="admin@faps.com"
# subject line. duh. 
#subject="Daily Synergy"


# Variables for building of buzz sentences 
# use 'past tense' ?
buzzverbs=( \
	"leveraged" \
	"promoted" \
	"used" \
	"pinged" \
	"prioritzed" \
	"increased" \
	"encouraged" \
	"road mapped" \
	"tabled" \
	"double-clicked"\
	"pulled on the thread of"
)


# can probably be duplicated from any other section. 
buzznouns=( \
    "synergy" \
    "shifting the paradigm" \
    "deep dives" \
	"deep diving" \
    "core competency" \
    "incentivization" \
    "the bleeding edge" \
    "my deliverables" \
    "action items" \
    "drilling down" \
    "low hanging fruit" \
	"thought leadership" \
	"cross team synergies" \
	"action plans" \
	"scrum planning" \
	"technical debt" \
	"data lake" \
	"server-less infrastructure" \
	"the cloud" \
	"kubernetes"\
)

# these should really tie the room together
buzzadjectives=( \
    "think outside the box" \
	"shift the paradigm" \
	"increase bandwidth" \
	"ideate" \
	"work in an agile methodology" \
	"increase productivity" \
	"promote thought leadership" \
	"leverage agile thought" \
	"decrease technical debt" \
	"generate tps reports" \
	"increase optics" \
	"raise the bar" \
)	

# Randomizes the selection of your buzz words
# if you want to really dial up the synergy or  spam your enemies, add in the while loop and set the sleep timer as desired 
# If you want to clog up a email relay add the while loop but disable the sleep timer. It's your lawsuit, pal.

while [ 1 ]
do 
noun=${buzznouns[ $((RANDOM % ${#buzznouns[@]} )) ]}
verb=${buzzverbs[ $((RANDOM % ${#buzzverbs[@]} )) ]}
adjective=${buzzadjectives[ $((RANDOM % ${#buzzadjectives[@]} )) ]}

# for my looping homies
#echo -e "Today I $verb $noun to $adjective \n\n\n sent via FAPS" | /bin/mailx -r $from -s "$subject" -b $distro 
# if you just want to run it in your terminal
echo -e "Today I $verb $noun to $adjective"


sleep 1
done

